# Generated by Django 3.0.5 on 2020-05-01 22:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20200501_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
